name: Compile Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore "Smash Forge.sln"
    
    - name: Build solution
      run: msbuild "Smash Forge.sln" -t:rebuild -property:Configuration=Release

    - name: Create Zip
      if: github.ref == 'refs/heads/master'
      working-directory: "Smash Forge/bin/Release"
      run: |
        Compress-Archive -path * -destinationPath Smash-Forge-Latest_Commit.zip

    - name: Upload Zip
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/master'
      with:
        files: "Smash Forge/bin/Release/Smash-Forge-Latest_Commit.zip"
        name: "Smash Forge [Latest Commit]"
        tag_name: "LatestCommit"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
